### ISSUE TITLE
Exception in get_instances method

### ISSUE THREAD

**Issue by alteralt** [Barahlush/vastai_client#41]
Module version: 0.1.1

Traceback :
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print(client.get_instances())
          ^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\vastai_client\vast_client.py", line 270, in get_instances
    return [from_dict(data_class=Instance, data=row) for row in rows]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\vastai_client\vast_client.py", line 270, in <listcomp>
    return [from_dict(data_class=Instance, data=row) for row in rows]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv\Lib\site-packages\dacite\core.py", line 69, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field_type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "disk_util" - should be "int | None" instead of value "0.36800000071525574" of type "float"
```

**Comment by maxiaoxiong** [comment]
@Barahlush Can you fix it? or i submit pr

**Comment by alteralt** [comment]
> @Barahlush Can you fix it? or i submit pr

If you are going to do PR, then here is a complete list of fields whose types I have corrected

```python
class Instance(VastaioClientInstance):
    ports: typing.Any = None
    disk_util: typing.Optional[typing.Union[int, float]] = None
    inet_down_billed: typing.Optional[typing.Union[bool, float]] = None
    inet_up_billed: typing.Optional[typing.Union[bool, float]] = None
    end_date: typing.Optional[typing.Union[str, float]] = None
    credit_balance: typing.Optional[str] = None
```
